version: "3.9"
services:
  discovery-server:
    image: restaurant_discovery
    build: ./discoveryServer
    ports:
      - "8000:8761"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:8761" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  config-server:
    image: restaurant_config
    build: ./config
    depends_on:
      discovery-server:
        condition: service_healthy
    ports:
      - "8001:8888"

  auth:
    image: restaurant_auth
    build: ./auth/server
    depends_on:
      - discovery-server
      - config-server
      - auth-db
    ports:
      - "8002:8080"
      - "5000:5005"

  auth-db:
    image: auth_postgres
    build: ./dbImage
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_MIGRATION_USER=${DB_MIGRATION_USER}
      - DB_MIGRATION_PWD=${DB_MIGRATION_PWD}
      - DB_NAME=${AUTH_DB_NAME}
      - DB_USER=${AUTH_DB_USER}
    ports:
      - "5432:5432"

#    volumes:
#      - auth_data_dev:/var/lib/postgresql/data

  inventory-db:
    image: inventory_postgres
    build: ./dbImage
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_MIGRATION_USER=${DB_MIGRATION_USER}
      - DB_MIGRATION_PWD=${DB_MIGRATION_PWD}
      - DB_NAME=${INVNTR_DB_NAME}
      - DB_USER=${INVNTR_DB_USER}
    ports:
      - "5433:5432"

  api-gateway:
    image: restaurant_gateway
    build: ./gateway
    depends_on:
      - discovery-server
      - config-server
    ports:
      - "8002:8080"
      - "5000:5005"

  pgAdmin:
    image: 'dpage/pgadmin4'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - "5433:80"

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "9093:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'

