server:
  port: 8005
spring:
  application:
    name: orders
  profiles:
    active: native
  config:
    import: "configserver"
  cloud:
    config:
      retry:
        max-attempts: 10
        max-interval: 5000
        multiplier: 1.51
        initial-interval: 2500
      fail-fast: true
      discovery:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
