server:
  port: 8001
spring:
  application:
    name: api-gateway
  profiles:
    active: frontend
  config:
    import: "configserver:"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

    config:
      retry:
        max-attempts: 10
        max-interval: 5000
        multiplier: 1.51
        initial-interval: 2500
      fail-fast: true
      discovery:
        enabled: true
eureka:
  instance:
    appname: api-gateway
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
