openapi: 3.0.3
info:
  title: Orders Service API
  description:
  version: 1.0.0
tags:
  - name: cart
    description: Everything about users cart
paths:
  /users:
    put:
      tags:
        - users
      description: Add a new user
      operationId: createUser
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: integer
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: string
          format: uuid
        fistName:
          type: string
        lastName:
          type: string
        createdAt:
          type: string
          format: datetime
        lastUpdated:
          type: string
          format: datetime

    OrderItem:
      type: object
      properties:
        id:
          type: string
          format: uuid
        fistName:
          type: string
        lastName:
          type: string
        createdAt:
          type: string
          format: datetime
        lastUpdated:
          type: string
          format: datetime

    OperationResult:
      type: object
      properties:
        success:
          type: boolean
        messages:
          type: array
          items:
            type: string

    ServerMessage:
      type: object
      properties:
        severity:
          $ref: '#/components/schemas/Severity'
        code:
          type: string
        message:
          type: string

    Severity:
      type: string
      enum:
        - ERROR
        - WARNING
        - INFO
